### ISSUE TITLE
[Question] why interpipe in rtmp-slate-fallback

### ISSUE THREAD

**Issue by ldenoue** [centricular/rtmp-slate-fallback#1]
Mathieu,

I noticed you use InterPipe plugin in this example.
Would it be possible to implement something similar using GstProxy or InterVideoSrc/Sink?

**Comment by MathieuDuponchelle** [comment]
@ldenoue this was written on demand, these days I would recommend using a combination of fallbacksrc and appsrc / appsink for sandboxing if needed.

It just so happens that we're about to make a project around that approach public, if you'll just hang tight for a week or two I'll update this issue with a link :)

Closing for now because nothing activatable.
